#SPDX-License-Identifier: MIT-0
---
# tasks file for system-manager


- name: Manage software packages
  include_tasks: packages.yml

- name: Manage users and groups
  include_tasks: users.yml

- name: Manage Git repositories
  include_tasks: git.yml

- name: Manage directory structure
  include_tasks: directories.yml
